@startuml

start
  #lightgreen:房态转换逻辑START;
  :房态为空时，返回不展示;
  :如果是满房，转换成满房;
  :如果是有房，转换成有房;
  :如果是可用，转换成有房;
  :如果是不可用(日期、星期)，转换成满房;
  :如果是不可用连住时间，转换成暂不可订;
  :如果是不可售状态，转换成暂不可订;
  :其他情况，包括无效和未知，返回不展示;
  #lightgreen:房态转换逻辑END;
stop

@enduml